# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='doc',
            field=models.FileField(blank=True, upload_to='Doc/'),
        ),
    ]
