# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-15 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_libro_vendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=180, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=96, verbose_name='slug')),
            ],
            options={
                'verbose_name_plural': 'Géneros',
                'verbose_name': 'Género',
            },
        ),
        migrations.RemoveField(
            model_name='libro',
            name='generos',
        ),
        migrations.AddField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(blank=True, to='books.Genero'),
        ),
    ]
